### ISSUE TITLE
command: '[/tmp/static-tcpdump -i any -U -w - ]' executing successfully exitCode: '125'

### ISSUE THREAD

**Issue by yashbhutwala** [eldadru/ksniff#102]
```INFO[0006] command: '[docker --host unix:///host/var/run/docker.sock run --rm --name=ksniff-container-DuJANPie --net=container:d85aa8a04c2b805fb451a22f5b33bb4fc780737952951098d1265c990aadcc54 maintained/tcpdump -i any -U -w - ]' executing successfully exitCode: '125', stdErr :'docker: Cannot connect to the Docker daemon at unix:///host/var/run/docker.sock. Is the docker daemon running?.```

**Comment by bostrt** [comment]
Hi @yashbhutwala would you mind retrying with the latest master branch? There are some fixes in there in regards to paths to docker sockets.

**Comment by yashbhutwala** [comment]
Yes latest version works, thanks @bostrt
