### ISSUE TITLE
Privileged pod can't be created on Kubernetes 1.20 (v1.20.5-gke.101)

### ISSUE THREAD

**Issue by hendrikmaus** [eldadru/ksniff#109]
I am trying to create a privileged pod on Kubernetes 1.20 (`v1.20.5-gke.101`) using the `-p` option and `knsiff` will run into a timeout error.
Inspecting the pod, it tries to create, yields: 

```
MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a file
```

**Comment by bostrt** [comment]
Hi @hendrikmaus,

Thanks for reporting this issue! Can yo please try specifying the `--socket /run/docker.sock` flag to see if that helps? If not, can you try SSH'ing to one of your nodes and checking where the `docker.sock` file really lives?

**Comment by hendrikmaus** [comment]
Sry for the delay, `docker.sock` lives in `/run/docker.dock` on those machines, however `/var/run` is a symlink to `/run`.

And I must apologize: I was using an older version of sniff; I upgraded to the latest and the issue is resolved.
