### ISSUE TITLE
ksniff is not supported in mbp m1

### ISSUE THREAD

**Issue by Delacroix** [eldadru/ksniff#117]
$ kubectl krew install sniff
Updated the local copy of plugin index.
Installing plugin: sniff
W0727 11:18:05.386333   58255 install.go:164] failed to install plugin "sniff": plugin "sniff" does not offer installation for this platform
F0727 11:18:05.386387   58255 root.go:79] failed to install some plugins: [sniff]: plugin "sniff" does not offer installation for this platform

---------
When I tried to install ksniff with krew on Macbook Pro M1(OS release: BigSur 11.5), it says platform not supported.

**Comment by bostrt** [comment]
@Delacroix I'm not familiar with building for Apple M1 (beyond knowing its ARM based). If possible, can you please try building ksniff like this and testing with the resulting binary?

```
$ git clone https://github.com/eldadru/ksniff.git
$ cd ksniff
$ GO111MODULE=on GOOS=darwin GOARCH=arm64 go build -o kubectl-sniff-darwin cmd/kubectl-sniff.go
```

**Comment by Delacroix** [comment]
> @Delacroix I'm not familiar with building for Apple M1 (beyond knowing its ARM based). If possible, can you please try building ksniff like this and testing with the resulting binary?
> 
> ```
> $ git clone https://github.com/eldadru/ksniff.git
> $ cd ksniff
> $ GO111MODULE=on GOOS=darwin GOARCH=arm64 go build -o kubectl-sniff-darwin cmd/kubectl-sniff.go
> ```

Thank you! After trying this, problem solved!

**Comment by Delacroix** [comment]
problem solved
