### ISSUE TITLE
Update Krew Index with v1.6.1

### ISSUE THREAD

**Issue by dntosas** [eldadru/ksniff#124]
Hey @eldadru, thanks for you nice job in here :)

Would be possible to update the version of the plugin into Krew Index so https://github.com/eldadru/ksniff/issues/114 is mitigated?

**Comment by dntosas** [comment]
I tried to open a PR in Krew directly but it seems on latest release the zip file was never published to calculate the sha256 needed

**Comment by mindw** [comment]
Travis.org is dead - 
![image](https://user-images.githubusercontent.com/578872/132986590-a1ff75be-5c32-4f68-9f5b-02b95024ac17.png)
So it may be that the tag zip upload never happened for 1.6.1?

**Comment by bostrt** [comment]
That's my mistake. I'll work on fixing this unless eldadru gets to it first.

**Comment by bostrt** [comment]
Pending https://github.com/kubernetes-sigs/krew-index/pull/1560

**Comment by bostrt** [comment]
v1.6.1 is now published in the Krew index. Apologies on missing this, I've opened https://github.com/eldadru/ksniff/pull/126 to automate this in GitHub Actions now instead of non-existent travis-ci.org :)
