### ISSUE TITLE
support tshark?

### ISSUE THREAD

**Issue by roostergr** [eldadru/ksniff#154]
Hi,
any chance ksniff will support also tshark in the near future?

Cheers

**Comment by bostrt** [comment]
Hi! It's not in the roadmap for the near future and no research has been done on how it would work exactly but I can see the value for users that want an interactive experience without a GUI. 

In the meantime you can use the -o flag to save a pcap and then review it in tshark.

**Comment by roostergr** [comment]
Hey thanks!
I can verify that I can review the file on tshark.
