### ISSUE TITLE
support containers running as non-privileged user

### ISSUE THREAD

**Issue by eldadru** [eldadru/ksniff#20]
Tcpdump execution requires root, some containers runs as non-root user, support those use-cases as well.

**Comment by jordanwilson230** [comment]
@eldadru would this workaround help? https://github.com/jordanwilson230/kubectl-plugins#kubectl-ssh

**Comment by eldadru** [comment]
Hi @jordanwilson230 I finally have the time to work on this issue, 
I would like ksniff to also support scratch containers so i will use similar approach to what kubectl-ssh does except I won't exec into the target container but attach to his network namespace and perform the actual sniffing on the attached container.

**Comment by eldadru** [comment]
Completed as part of #30 , please play with it, test it and report bugs :)

**Comment by adipascu** [comment]
I am getting `static-tcpdump: any: You don't have permission to capture on that device` on a nginx container that defaults to running as the `www-data` user.

I am running knsiff 1.3.1

**Comment by eldadru** [comment]
@adipascu add "-p" to your command line to invoke ksniff in privileged mode

**Comment by adipascu** [comment]
Thanks!  @eldadru why not do it privileged by default?

**Comment by Ri1a** [comment]
> @adipascu add "-p" to your command line to invoke ksniff in privileged mode

Getting the following error message:
```
ERRO[0000] failed to create privileged pod on node: 'minikube'  error="pods \"ksniff-vjtdw\" is forbidden: violates PodSecurity \"baseline:latest\": host namespaces (hostPID=true), hostPath volumes (volumes \"host\", \"container-socket\"), privileged (container \"ksniff-privileged\" must not set securityContext.privileged=true)"
Error: pods "ksniff-vjtdw" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostPID=true), hostPath volumes (volumes "host", "container-socket"), privileged (container "ksniff-privileged" must not set securityContext.privileged=true)
```

K8s version: v1.23.3

**Comment by darktempla** [comment]
Not sure if it helps but ephemeral containers might allow you provide an image with everything you need already baked in and attach it to the pod/container to sniff.

https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/
