### ISSUE TITLE
Error compiling static-tcpdump on Mac

### ISSUE THREAD

**Issue by jordanwilson230** [eldadru/ksniff#22]
```make darwin``` works fine, but ```make static-tcpdump``` gives the following output:

```
cd tcpdump-4.9.2 && CFLAGS=-static ./configure --without-crypto && make
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/jordan/git/ksniff/tcpdump-4.9.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [static-tcpdump] Error 77
```

The config.log output: [config.log](https://github.com/eldadru/ksniff/files/2747326/config.log)

Also note that running the plugin via Krew results in another error: https://github.com/GoogleContainerTools/krew-index/issues/48

The error I see when running via krew seems related to the other open issue here: https://github.com/eldadru/ksniff/issues/21

**Comment by eldadru** [comment]
First, thank you very much for using and reporting issues in ksniff!

Regard tcpdump compilation failure: at the moment "make static-tcpdump" isn't supported and not really needed for macOS machines - ksniff use static tcpdump to sniff on remote containers which are mostly running on x64 Linux machines.

The required static-tcpdump binary is shipped alongside ksniff in both krew and on the release package.
If you'd like, you can also examine the compilation process in the project's travis page: 
https://travis-ci.org/eldadru/ksniff

Regard the second error you experienced, I think I resolved that as part of #21 , please see my comment there for more information.

Please try the new version and update if that resolves your issue

**Comment by jordanwilson230** [comment]
Thanks, @eldadru! I will give it a shot sometime today.

**Comment by jordanwilson230** [comment]
@eldadru its working great, very neat!  I see it won't run on non-privileged containers (understandable), but was wondering if there might be someway that you could combine a part of my plugin ```kubectl krew install exec-as``` as a workaround?  It will connect to any pod as root, regardless of privileges set on the container.  The code is [here](https://github.com/jordanwilson230/kubectl-plugins/blob/master/kubectl-ssh) if you want to take a look.

**Comment by eldadru** [comment]
Awesome!

Regard non-privileged containers - that what I had in mind, I came by your plugin and planned to use the same technique for ksniff as well. I'm trying to find a solution that will work for scratch containers as well.

Anyway, I'm closing this issue, lets continue the non-privileged discussion on #20
