### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by StianOvrevage** [eldadru/ksniff#27]
Installed ksniff in Ubuntu on WSL (Windows subsystem for Linux) but it does not run, or give any useful information:

```
$ k sniff shell-7f7f4fb5cb-bpc7p
cannot allocate memory
$ k sniff shell-7f7f4fb5cb-bpc7p -o myfile
cannot allocate memory
```

**Comment by eldadru** [comment]
@StianOvrevage thanks for using ksniff and reporting this issue :)
Personally, I never tested ksniff on WSL, I did tried ksniff on native windows machine and it worked.

I tried to look for the error string and found many similar issues, i.e:
https://github.com/Microsoft/WSL/issues/1019
https://github.com/Microsoft/WSL/issues/1563

I believe it's a WSL issue
Anyway, can you please try to run ksniff with -v (verbose) and post the output here.

**Comment by eldadru** [comment]
Closing this issue, if issue reproduced please open another issue
