### ISSUE TITLE
automatically open pull request for new version for krew-index

### ISSUE THREAD

**Issue by eldadru** [eldadru/ksniff#32]
Ksniff can be installed as part of the krew kubectl plugin manager.
krew use krew-index (https://github.com/GoogleContainerTools/krew-index) a repository that used as krew plugin store, each plugin has it's own yaml file with the plugin description that includes its version, its binary package location and its hash.

In order to upgrade a plugin in krew one has to update the plugin yaml to have the latest information and open a pull request for the krew-index project.

I'd like this process to be automatic on each time we merge ksniff to master and build a plugin release

**Comment by grzesuav** [comment]
@eldadru do you have any idea in mind ? 

Because there exist tool exactly for that : https://github.com/renovatebot/renovate/

but support for krew plugins files would need to be added.

**Comment by rajatjindal** [comment]
Hi @eldadru 

I have created [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) to auto publish new plugin releases to krew-index repo.

If its ok with you, I can open a PR to start using that for auto publishing the releases or you can look at the [travis](https://github.com/rajatjindal/krew-release-bot/blob/master/examples/travis.yml) example here, and configure it.

Many thanks for considering.
Rajat Jindal

**Comment by eldadru** [comment]
@rajatjindal that's a great idea, please open the PR, thanks!

**Comment by rajatjindal** [comment]
opened pr #56

**Comment by eldadru** [comment]
@rajatjindal - great work, thanks again! closing this issue.
