### ISSUE TITLE
Support privileged mode for CRI-O runtime

### ISSUE THREAD

**Issue by xt99** [eldadru/ksniff#36]
Hello there!

We are using OpenShift with default security in place so we have no option not to use ksniff privileged mode. But also we're using CRI-O instead of Docker runtime. Currently ksniff supports only Docker runtime for privileged mode. Do you have any plans to support CRI-O  runtime for privileged mode?

PS: Thanks for a great tool!

**Comment by eldadru** [comment]
Hi @xt99 ,

Thanks for using ksniff and opening this issue.

CRI-O support wasn't on the roadmap, I'll take a quick look to understand what it requires and update here.
