### ISSUE TITLE
Couldn't run /usr/bin/dumpcap in child process: Permission denied

### ISSUE THREAD

**Issue by karlmutch** [eldadru/ksniff#40]
Running sniff in a privileged, or unprivileged pod results in the wireshark client posting an error dialog box, "Couldn't run /usr/bin/dumpcap in child process: Permission denied".  Examining the target pod I find this executable is not present in both the priv and unpriv cases.

I think modified the Dockerfile to pull in wireshark-common and now get 'operation not permitted'.

These containers are running in a Kubernetes 1.11.1 cluster, using on AWS EC2 nodes provisioned using kops 1.11.1.

Any thoughts ?

**Comment by eldadru** [comment]
Hi @karlmutch,

Thanks for using Ksniff and posting this issue!

It seems like wireshark related issue, specifically permissions issue, take a look here:
https://askubuntu.com/questions/458762/how-to-enable-wireshark-without-running-as-root-in-trusty-14-04

Eldad

**Comment by karlmutch** [comment]
Thanks for the suggestions I incorporated them but had no luck.  I also added a setcap command:

```
setcap cap_net_raw,cap_net_admin+eip /usr/bin/dumpcap
```

To no avail.  I have had other things interrupt and had to move to the next thing but thought I'd include references for the future in the event anyone has bandwidth to retest.

https://wiki.wireshark.org/CaptureSetup/CapturePrivileges#Debian.2C_Ubuntu_and_other_Debian_derivatives
https://github.com/jessfraz/dockerfiles/blob/master/wireshark/Dockerfile

Thanks for the suggestions.  Please leave, close etc as you desire.
