### ISSUE TITLE
Travis Script does not call go test

### ISSUE THREAD

**Issue by ryancox** [eldadru/ksniff#46]
CI should run tests. This could be added explicitly in the yaml or as a new dependency in the Makefile

**Comment by eldadru** [comment]
Totally agree - tests should always run as part of the CI.

That what I'm implementing as part of https://github.com/eldadru/ksniff/tree/31-add-end-to-end-tests

Beside UT, it will include e2e test suite - spin up a local k8s cluster - sniff on remote pods both in the tcpdump upload and privileged mode and check output.
