### ISSUE TITLE
Error: No Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by binnythomas-1989** [eldadru/ksniff#52]
When i run kubectl sniff i get this, no documentation to show how to fix this.

**Comment by binnythomas-1989** [comment]
@eldadru  Any update on this would be deeply appreciated.

**Comment by binnythomas-1989** [comment]
@eldadru Would be great if we could get an update?

**Comment by eldadru** [comment]
I started digging into this one, I think it's pretty straight forward, I'll try to merge my fix in the near days.
See: https://github.com/eldadru/ksniff/tree/52-support-azure

**Comment by binnythomas-1989** [comment]
Thanks man! Appreciate it. @eldadru

**Comment by eldadru** [comment]
I merged #62 to have azure support, @binnythomas-1989 please confirm it resolves this issue.

**Comment by binnythomas-1989** [comment]
@eldadru  Good job mate! It works now.. Really useful. 
@nfoerster  Please reinstall ksniff and retry now it should be okay.
