### ISSUE TITLE
Couldn't run /usr/sbin/dumpcap in child process: Permission denied

### ISSUE THREAD

**Issue by sshayb** [eldadru/ksniff#57]
Getting this from wireshark after trying to use ksniff for the first time "kubectl sniff <podid>":

Couldn't run /usr/sbin/dumpcap in child process: Permission denied
Are you a member of the 'wireshark' group? Try running
'usermod -a -G wireshark _your_username_' as root.

Interfaces on the wireshark screen appear to be "null". 
When executing "kubectl exec <podid> -it id" I am getting root.

**Comment by eldadru** [comment]
Did you execute 'usermod -a -G wireshark your_username' as root.' as root?

It requires in order to successfully run wireshark without sudo
