### ISSUE TITLE
allow for customizing the wireshark command executed

### ISSUE THREAD

**Issue by joemiller** [eldadru/ksniff#58]
Would you consider an option to allow for specifying an alternative to the exec'ing the wireshark GUI?

For example, I think it would be interesting to run sniff and connect the pcap output to tshark or https://github.com/gcla/termshark 

I'd be happy to work on a PR for this if it is something you would be OK including.

Perhaps via a flag like `-w/--wireshark-bin=/path`

**Comment by eldadru** [comment]
Sure, feel free to open a PR.

I think it will be more "unix idiomatic" to export ksniff pcap output to stdout and pipe it to another tool for display - what do you think?

**Comment by joemiller** [comment]
@eldadru That makes sense to me. It looks like this is already happening with wireshark. 

Are you proposing a generic option to pipe ksniff's output to stdout instead an option to start another binary? maybe something like:

```console
$ kubectl sniff statsd-ingest-5cd8459676-82472 -f "port 8125" -o - | tshark -r -
```

**Comment by eldadru** [comment]
@joemiller - that was exactly my intention, thanks for taking the time to implement this feature and supporting ksniff!
