### ISSUE TITLE
How to troubleshoot distroless images

### ISSUE THREAD

**Issue by y0zg** [eldadru/ksniff#67]
It's not an issue at all, but I wonder what  are the options rather than change the image if I need to sniff the traffic on distroless image

**Comment by eldadru** [comment]
Hi @y0zg , I'm sorry to respond so late to your question.

The privilege mode (-p) should work for distroless containers as well as scratch containers.

**Comment by y0zg** [comment]
distroless images also have `:debug` option which provides a busybox shell to enter
