### ISSUE TITLE
Error when run ksniff in privileged mode and ksniff isn't the first container of the pod

### ISSUE THREAD

**Issue by ffais** [eldadru/ksniff#84]
Hi,
I'm trying to use ksniff with Istio 1.7.3 with config option `values.global.proxy.holdApplicationUntilProxyStart ` enabled, which causes the sidecar injector to inject the sidecar at the start of the pod’s container list.

I'm now getting the following error.
```
INFO[0010] executing command: '[docker --host unix:///host/var/run/docker.sock run --rm --name=ksniff-container-dKHBrsxq --net=container:ab652c801a2616a5f47603054cdfc579eb4a403f4597c4b08f146f58d0c71ee9 maintained/tcpdump -i any -U -w - ]' on container: 'istio-proxy', pod: 'ksniff-zzk4m', namespace: 'global' 
INFO[0011] command: '[docker --host unix:///host/var/run/docker.sock run --rm --name=ksniff-container-dKHBrsxq --net=container:ab652c801a2616a5f47603054cdfc579eb4a403f4597c4b08f146f58d0c71ee9 maintained/tcpdump -i any -U -w - ]' executing successfully exitCode: '126', stdErr :''
```

I try with this temporary workaround and everything is working fine (sorry but I'm not a developer).
https://github.com/ffais/ksniff/blob/62b535a9cc068d25eb6d31bde8ad20308490b42a/pkg/service/sniffer/privileged_pod_sniffer_service.go

**Comment by bostrt** [comment]
Yep, looks like Istio can automatically injecting sidecar as first container as you suggested. I think you're along the right path in using the `ksniff-privleged` container name instead of trying to pull it from the container list in the Pod. 

@ffais would you like to submit a PR or leave it to ksniff devs to make the change?

**Comment by ffais** [comment]
@bostrt I have submitted a PR, hope will be helpful.

**Comment by CathalC2011** [comment]
Would be great to that get that PR merged! This is also hitting us. Not using AKS, but I don't think that part is relevant.

**Comment by bostrt** [comment]
Hi all, this was merged so closing out this issue. It'll make it into the next release which I hope to tag this month.
