### ISSUE TITLE
Error: exec: "wireshark": executable file not found in $PATH

### ISSUE THREAD

**Issue by muhammad-fahad2068** [eldadru/ksniff#88]
Hi, I am using macos and i have installed wireshark

I tried sniffing one of my pods using the command

kubectl sniff pod-name -n namespace

and below is where its erroring out

Error: exec: "wireshark": executable file not found in $PATH

can you let me know how this can be resolved in macos

**Comment by slient2010** [comment]
+1, MacOS can't find the wireshark $PATH.

here is my solution, hope it can help you.

1. open your terminal(or iterm) on MacOS.

2. add a file named `wireshark` with contents below.
```bash
cd /usr/local/bin/
sudo vim wireshark
```
add those contents to your `wireshark` file and save it.
```text
#!/usr/bin/env bash
WIRESHARK="/Applications/Wireshark.app/Contents/MacOS/Wireshark"
${WIRESHARK} "$@"
exit $?
```

3. chmod the `wireshark` file.
```bash
cd /usr/local/bin/
chmod a+x wireshark
```

4. try again, this tool will work.

```bash
kubectl sniff pod-xxx -n xxx
```

**Comment by bostrt** [comment]
Closing this out assuming @slient2010's reply solve the issue. If you are still having problems, please reopen @muhammad-fahad2068!

**Comment by RM250702** [comment]
I have similar issue in my windows. Please help me..thanks
time="2021-08-22T23:43:38+05:30" level=info msg="file found: '-rw-rw-rw- 1 root root 2696368 Aug 22 18:02 /tmp/static-tcpdump\n'"
time="2021-08-22T23:43:38+05:30" level=info msg="file was already found on remote pod"
time="2021-08-22T23:43:38+05:30" level=info msg="tcpdump uploaded successfully"
time="2021-08-22T23:43:38+05:30" level=info msg="spawning wireshark!"
time="2021-08-22T23:43:38+05:30" level=info msg="starting sniffer cleanup"
time="2021-08-22T23:43:38+05:30" level=info msg="sniffer cleanup completed successfully"
Error: exec: "wireshark": executable file not found in %PATH%
Error: exit status 1
