### ISSUE TITLE
Lighter runtime footprint

### ISSUE THREAD

**Issue by scodeman** [eldadru/ksniff#94]
Running the plugin, ksniff containers are remaining on disk with a fair amount of disk space due to logging of standard output on  disk.
Suggestion for docker runtime is to:
- make docker call ephemeral with `--rm` argument
- make the network capture stdout not saved on file with `--log-driver none` option

**Comment by scodeman** [comment]
Pull request #95

**Comment by bostrt** [comment]
#95 merged :smiley:
