### ISSUE TITLE
Need info on if this tool is Prod ready currently and reasons why this shouldnt be used in prod

### ISSUE THREAD

**Issue by tarangini-shetty** [eldadru/ksniff#96]
Hi Team,

I kind of used this tool in my test setup. 
Since I see in Readme of this repo that it's not ready for prod. Any info on why this shouldnt be used in prod. If in case those reasons doesnt apply to the cluster we are trying with, should it be ok to use in prod?
Thoughts on this might help me decide on usage of this tool further.

Thank you in advance.

**Comment by bostrt** [comment]
Hi @tarangini-shetty afaik the production-readiness of ksniff is in regards to how stable its API is (command line flags, etc) and that it may not be stable enough to integrate into scripting used in prod.

If there's a security reason then I would have to defer to @eldadru to answer that.

While we're on the topic, I'll make a note of submitting a PR for including things like https://github.com/securego/gosec into ksniff CI.

**Comment by eldadru** [comment]
Hi all,

ksniff was never tested for performance, also - the privilege mode "breaks" out of the scope of Kubernetes and may leave stale containers on your production hosts.

**Comment by bostrt** [comment]
Hi @tarangini-shetty, I'm going to go ahead and close this but let us know if you have any more questions.

**Comment by russe-g** [comment]
Hi everyone!
I have a question regarding this answer from @eldadru :

> "the privilege mode "breaks" out of the scope of Kubernetes and may leave stale containers on your production hosts."

Wouldn't this be applicable only if I use the "-p" flag?
In other words: Would ksniff be production ready (apart from the possible performance issue) if I don't use the "-p" flag?
