### ISSUE TITLE
Protocol detection doesn't work

### ISSUE THREAD

**Issue by Pepsi1k** [eldadru/ksniff#98]
When I run wireshark on local machine all works fine.
But when i run `kubectl sniff -n <namespace> <pod> -p`, i see that: 

![image](https://user-images.githubusercontent.com/36175709/105378368-6a73b000-5c14-11eb-84ca-d46a93194d7a.png)

Any idea?

**Comment by FaKod** [comment]
@Pepsi1k Have you found a solution?

**Comment by Pepsi1k** [comment]
@FaKod Yes. The problem was in previous versions of wireshark. I installed `wireshark 3.5` and it works fine
